pull request
gall0ws/freeRep pull request #1
Opened 2020-11-07 21:18 UTC by AnonHexo

ho modificato il tuo script e l'ho reso un pochetto più semplice e veloce quello che ho fatto l'ho commentato nello script ;)

2020-11-08 19:43 UTC, gall0ws commented
Grazie per l'interessamento!

Accetto la riga 4, perché effettivamente i contenuti dietro paywall stanno sempre sotto quel path.
Però devi modificare il commit includendo solo quel cambiamento (senza ulteriori commenti, è chiaro il motivo).

Per il resto, il codice attuale funziona e soprattutto è leggibile, modulare e facilmente modificabile. A meno che tu non abbia trovato problemi specifici non ho motivo di cambiarlo.

Minificarlo non ha nessun vero vantaggio, perché comunque gira localmente.

Consigli in generale per le pull request:

- Non mettere commenti nel commit per spiegare il motivo dei cambiamenti, rende la PR non accettabile.
- Non stravolgere il codice originale, a meno di validi motivi.
- Usa un titolo più descrittivo.

2020-11-08 19:49 UTC, gall0ws requested changes
Accetto la riga 4, perché effettivamente i contenuti dietro paywall stanno sempre sotto quel path.
Però devi modificare il commit includendo solo quel cambiamento (senza ulteriori commenti, è chiaro il motivo).

2020-11-09 06:56 UTC, valepert commented
> Accetto la riga 4, perché effettivamente i contenuti dietro paywall stanno sempre sotto quel path.

andrebbe anche allineato [manifest.json:12](https://github.com/gall0ws/freeRep/blob/master/manifest.json#L12)

2020-11-10 13:18 UTC, AnonHexo commented
oh, pensavo non la vedessi neanche la PR visto che è di 2 anni ma ma mi sbagliavo... comunque, ok!

2021-01-03 11:39 UTC, closed without merging

2021-01-03 11:39 UTC, gall0ws commented
Repubblica adesso mette dietro paywall anche articoli non appartenenti a "rep".
Chiudo come invalida.